### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by findell666** [sbv-solutions-private-limited/Ofbiz-React-UI#4]
Hello, 
I did npm install and I have this error : 

```
Building the Webpack DLL...
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/webpack/lib/util/createHash.js:75:53)
    at NormalModule._initBuildHash (/home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/webpack/lib/NormalModule.js:403:16)
    at handleParseError (/home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/webpack/lib/NormalModule.js:451:10)
    at /home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/webpack/lib/NormalModule.js:483:5
    at /home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/webpack/lib/NormalModule.js:344:12
    at /home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /home/clement/progessi/ofbiz/OFBiz-React-UI/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

then I tried npm start, I have this error :

`The DLL manifest is missing. Please run 'npm run build:dll'`

Node.js v18.10.0
Npm v8.19.2
Ubuntu 20.04.5

Thank you for your help

**Comment by findell666** [comment]
Nervermind, I fixed it by executing this line before npm install :
`export NODE_OPTIONS=--openssl-legacy-provider`
